# Generated by Django 5.2.6 on 2025-11-18 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activa', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=40, verbose_name='nombre')),
                ('descripcion_cat', models.TextField(verbose_name='descipcion')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_serv', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion_serv', models.TextField()),
                ('img_serv', models.ImageField(upload_to='servicio/')),
                ('precio_serv', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=60, verbose_name='producto')),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('descripcion_prod', models.TextField(verbose_name='descipcion')),
                ('img_prod', models.ImageField(upload_to='producto/')),
                ('beneficio_prod', models.CharField(max_length=200)),
                ('stock', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej:'Oferta de Invierno', 'Liquidación Final' ", max_length=100)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuentos(ej: 15 para un 15%)', max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=False)),
                ('productos', models.ManyToManyField(blank=True, related_name='ofertas', to='core.producto')),
            ],
            options={
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (mayor número = más prioritario)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destacados', to='core.producto', verbose_name='Producto destacado')),
            ],
            options={
                'verbose_name': 'Producto destacado',
                'verbose_name_plural': 'Productos destacados',
                'ordering': ['-orden', '-fecha_creacion'],
            },
        ),
    ]
